[2024-12-07T03:28:46.775-0300] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2024-12-07T03:28:46.784-0300] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: hiring_dynamic_pipeline.decide_datasets scheduled__2024-10-05T15:00:00+00:00 [queued]>
[2024-12-07T03:28:46.789-0300] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: hiring_dynamic_pipeline.decide_datasets scheduled__2024-10-05T15:00:00+00:00 [queued]>
[2024-12-07T03:28:46.789-0300] {taskinstance.py:2866} INFO - Starting attempt 2 of 3
[2024-12-07T03:28:47.436-0300] {taskinstance.py:2889} INFO - Executing <Task(BranchPythonOperator): decide_datasets> on 2024-10-05 15:00:00+00:00
[2024-12-07T03:28:47.443-0300] {standard_task_runner.py:72} INFO - Started process 43745 to run task
[2024-12-07T03:28:47.446-0300] {standard_task_runner.py:104} INFO - Running: ['airflow', 'tasks', 'run', 'hiring_dynamic_pipeline', 'decide_datasets', 'scheduled__2024-10-05T15:00:00+00:00', '--job-id', '46', '--raw', '--subdir', 'DAGS_FOLDER/dag_dynamic.py', '--cfg-path', '/tmp/tmpaidmurlx']
[2024-12-07T03:28:47.446-0300] {standard_task_runner.py:105} INFO - Job 46: Subtask decide_datasets
[2024-12-07T03:28:48.623-0300] {task_command.py:467} INFO - Running <TaskInstance: hiring_dynamic_pipeline.decide_datasets scheduled__2024-10-05T15:00:00+00:00 [running]> on host crisu-VivoBook-S14-X411UF
[2024-12-07T03:28:49.676-0300] {taskinstance.py:3132} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='hiring_dynamic_pipeline' AIRFLOW_CTX_TASK_ID='decide_datasets' AIRFLOW_CTX_EXECUTION_DATE='2024-10-05T15:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-10-05T15:00:00+00:00'
[2024-12-07T03:28:49.679-0300] {logging_mixin.py:190} INFO - Task instance is in running state
[2024-12-07T03:28:49.679-0300] {logging_mixin.py:190} INFO -  Previous state of the Task instance: queued
[2024-12-07T03:28:49.679-0300] {logging_mixin.py:190} INFO - Current task name:decide_datasets state:running start_date:2024-12-07 06:28:46.784553+00:00
[2024-12-07T03:28:49.680-0300] {logging_mixin.py:190} INFO - Dag name:hiring_dynamic_pipeline and current dag run status:running
[2024-12-07T03:28:49.680-0300] {taskinstance.py:731} INFO - ::endgroup::
[2024-12-07T03:28:49.680-0300] {baseoperator.py:416} WARNING - BranchPythonOperator.execute cannot be called outside TaskInstance!
[2024-12-07T03:28:49.681-0300] {taskinstance.py:3311} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/crisu/miniconda3/envs/lab13.1/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
  File "/home/crisu/miniconda3/envs/lab13.1/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
  File "/home/crisu/miniconda3/envs/lab13.1/lib/python3.9/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
  File "/home/crisu/miniconda3/envs/lab13.1/lib/python3.9/site-packages/airflow/models/baseoperator.py", line 417, in wrapper
    return func(self, *args, **kwargs)
  File "/home/crisu/miniconda3/envs/lab13.1/lib/python3.9/site-packages/airflow/operators/python.py", line 274, in execute
    return self.do_branch(context, super().execute(context))
  File "/home/crisu/miniconda3/envs/lab13.1/lib/python3.9/site-packages/airflow/models/baseoperator.py", line 417, in wrapper
    return func(self, *args, **kwargs)
  File "/home/crisu/miniconda3/envs/lab13.1/lib/python3.9/site-packages/airflow/operators/python.py", line 238, in execute
    return_value = self.execute_callable()
  File "/home/crisu/miniconda3/envs/lab13.1/lib/python3.9/site-packages/airflow/operators/python.py", line 256, in execute_callable
    return runner.run(*self.op_args, **self.op_kwargs)
  File "/home/crisu/miniconda3/envs/lab13.1/lib/python3.9/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
  File "/home/crisu/Universidad/MDS7202-Primavera2024/Lab 13 - Airflow/dags/dag_dynamic.py", line 22, in decide_which_datasets
    execution_date = datetime(kwargs['ds'])
TypeError: an integer is required (got type str)
[2024-12-07T03:28:50.619-0300] {logging_mixin.py:190} INFO - Task instance in failure state
[2024-12-07T03:28:50.619-0300] {logging_mixin.py:190} INFO - Task start:2024-12-07 06:28:46.784553+00:00 end:2024-12-07 06:28:50.618927+00:00 duration:3.834374
[2024-12-07T03:28:50.619-0300] {logging_mixin.py:190} INFO - Task:<Task(BranchPythonOperator): decide_datasets> dag:<DAG: hiring_dynamic_pipeline> dagrun:<DagRun hiring_dynamic_pipeline @ 2024-10-05 15:00:00+00:00: scheduled__2024-10-05T15:00:00+00:00, state:running, queued_at: 2024-12-07 06:27:03.158666+00:00. externally triggered: False>
[2024-12-07T03:28:50.620-0300] {logging_mixin.py:190} INFO - Failure caused by an integer is required (got type str)
[2024-12-07T03:28:50.620-0300] {taskinstance.py:1225} INFO - Marking task as UP_FOR_RETRY. dag_id=hiring_dynamic_pipeline, task_id=decide_datasets, run_id=scheduled__2024-10-05T15:00:00+00:00, execution_date=20241005T150000, start_date=20241207T062846, end_date=20241207T062850
[2024-12-07T03:28:51.722-0300] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2024-12-07T03:28:51.722-0300] {standard_task_runner.py:124} ERROR - Failed to execute job 46 for task decide_datasets (an integer is required (got type str); 43745)
Traceback (most recent call last):
  File "/home/crisu/miniconda3/envs/lab13.1/lib/python3.9/site-packages/airflow/task/task_runner/standard_task_runner.py", line 117, in _start_by_fork
    ret = args.func(args, dag=self.dag)
  File "/home/crisu/miniconda3/envs/lab13.1/lib/python3.9/site-packages/airflow/cli/cli_config.py", line 49, in command
    return func(*args, **kwargs)
  File "/home/crisu/miniconda3/envs/lab13.1/lib/python3.9/site-packages/airflow/utils/cli.py", line 116, in wrapper
    return f(*args, **kwargs)
  File "/home/crisu/miniconda3/envs/lab13.1/lib/python3.9/site-packages/airflow/cli/commands/task_command.py", line 483, in task_run
    task_return_code = _run_task_by_selected_method(args, _dag, ti)
  File "/home/crisu/miniconda3/envs/lab13.1/lib/python3.9/site-packages/airflow/cli/commands/task_command.py", line 256, in _run_task_by_selected_method
    return _run_raw_task(args, ti)
  File "/home/crisu/miniconda3/envs/lab13.1/lib/python3.9/site-packages/airflow/cli/commands/task_command.py", line 341, in _run_raw_task
    return ti._run_raw_task(
  File "/home/crisu/miniconda3/envs/lab13.1/lib/python3.9/site-packages/airflow/utils/session.py", line 97, in wrapper
    return func(*args, session=session, **kwargs)
  File "/home/crisu/miniconda3/envs/lab13.1/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 3005, in _run_raw_task
    return _run_raw_task(
  File "/home/crisu/miniconda3/envs/lab13.1/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 273, in _run_raw_task
    TaskInstance._execute_task_with_callbacks(
  File "/home/crisu/miniconda3/envs/lab13.1/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 3159, in _execute_task_with_callbacks
    result = self._execute_task(context, task_orig)
  File "/home/crisu/miniconda3/envs/lab13.1/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 3183, in _execute_task
    return _execute_task(self, context, task_orig)
  File "/home/crisu/miniconda3/envs/lab13.1/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
  File "/home/crisu/miniconda3/envs/lab13.1/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
  File "/home/crisu/miniconda3/envs/lab13.1/lib/python3.9/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
  File "/home/crisu/miniconda3/envs/lab13.1/lib/python3.9/site-packages/airflow/models/baseoperator.py", line 417, in wrapper
    return func(self, *args, **kwargs)
  File "/home/crisu/miniconda3/envs/lab13.1/lib/python3.9/site-packages/airflow/operators/python.py", line 274, in execute
    return self.do_branch(context, super().execute(context))
  File "/home/crisu/miniconda3/envs/lab13.1/lib/python3.9/site-packages/airflow/models/baseoperator.py", line 417, in wrapper
    return func(self, *args, **kwargs)
  File "/home/crisu/miniconda3/envs/lab13.1/lib/python3.9/site-packages/airflow/operators/python.py", line 238, in execute
    return_value = self.execute_callable()
  File "/home/crisu/miniconda3/envs/lab13.1/lib/python3.9/site-packages/airflow/operators/python.py", line 256, in execute_callable
    return runner.run(*self.op_args, **self.op_kwargs)
  File "/home/crisu/miniconda3/envs/lab13.1/lib/python3.9/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
  File "/home/crisu/Universidad/MDS7202-Primavera2024/Lab 13 - Airflow/dags/dag_dynamic.py", line 22, in decide_which_datasets
    execution_date = datetime(kwargs['ds'])
TypeError: an integer is required (got type str)
[2024-12-07T03:28:51.760-0300] {local_task_job_runner.py:266} INFO - Task exited with return code 1
[2024-12-07T03:28:51.779-0300] {taskinstance.py:3895} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-12-07T03:28:51.780-0300] {local_task_job_runner.py:245} INFO - ::endgroup::
